mode: deployment

image:
  repository: "otel/opentelemetry-collector-contrib"
  tag: "0.100.0"

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  exporters:
    prometheus:
      endpoint: "0.0.0.0:8889"
      namespace: "otel" # додасть префікс до метрик, щоб їх було легше шукати
    debug:
      verbosity: detailed

  service:
    pipelines:
      metrics:
        receivers: [otlp]
        processors: []
        exporters: [prometheus, debug] # додано debug, щоб ти бачив метрики в логах пода
