---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kbot
  namespace: kbot
spec:
  encryptedData:
    token: AgB+pCZ/xYZmqFa4fxCYb7NyMf5Fv8q4lRZjFG8GnNI73mMEx+yrzZitg7QbM+mpgR15EJpGbxUsEJc3pfrr/bd9IRtK4IAVaeixBc/NBEnN7bgTPmr4NUhBEMqzQHVpGuyma6nL0ymUzhf3lkJmpvuDKzhAS9WUepmH3sIBU/oFIvRGnMFTybOvgc2/qyxiGfAHXvsmjlOT5sD+Up3II1M9m/8rjMplYb2EZsiEtfTK39m9uh48x6w7ZAm9QnWja7v+vNuLxoVJySaGS6hHmMJTtqrr9Ytave1McPepXDF8L7p8jYIEGVsw1+jzVNhOGlxKWC1WdXhI8MIbvPkflbRv4MpKNJWq3sg412Os3QXhvQXjW5FzLOwl91lPS+txsGUj4mwLj5A7gSbT6GZpkbKE3M4dE12nX4T5jbireDoBDlkACgh+sRuI2rx38bxVISFRVneU5+dKo0PpoAt3LfbY3JNqcxjckzp8KY0ncWSN41DbD9c2RBWeUapLe99P5frLtl4X0Ul7tRNFupteuU2blLlLbO4mwxBTTjtYwPyGn0WPZCI38MebTazxBEuNbK7Fo/sLifDrInHad0+5eeojbPVYngPnjiFeACLeJ0/9UUXC/hYGb+nHGApWGjeaBAF+qGvoSPWkf4r0kF7SL5XKwCjbmyeoJMX6mIdKNeF8pu30lmTlbdWdIpZ8DcZHA9Cy+h6jzyRErAkLcQRlFzBg8eb7dXXBuGMDwHQjZ0tyJceH3a9Qt71tmkYXk+on
  template:
    metadata:
      name: kbot
      namespace: kbot
