---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kbot
  namespace: kbot
spec:
  encryptedData:
    token: AgAhzWPMoogBgeZQ+SE7ALXFHUqPn9lFq2wThkFIgYX7ETuKsU7MW7srMIbE7QFWNkUFfYJr+93oL00KfC9ulL7QSN3j+56X7FcBX8YHRSScs5cbHCy9nuqbWgoIh+3hESdY/bS7pUqd4OmvhM98Ycl35a4/a+5JERAu7VBknef+DMsBCIs6VClI22Jt4PXgM2pphpSCEmMXJx6tNxR+Eh+e/UNGe0KBzOtG9BnUfeNp2z4Mrorj5PVRex+naeL8UGR27SdGzdd/8tb44FgBm2J5c89en0V0vxnOFjQ5jkdWM3NZf6zNCOa938s/DwKOIEAz9v8O24VrHjmH0+tA3cyb6M0uPdlNDQb5esHZSz03NPtxkeBzXKh8zt81R9b95NwwjiAKQCo7RTQQvptZw3lz4r/jcqaEMjbNe3t8XTXZJ1gFK9zygMa4DVXifiJxEsRNiwQVnXVAEfuXaFTczqvyWEASd0vVu1010MYAl9CT9u/YsLKtK8eBDW44U1sZb/MALutvypKbYv/dUh2DYZ/lWIx/dW2S2Pj4zfFEHZZcGhfeNMNc0kGNUs0hMCyZ5Ca5C0r7lRcceaIWluiEeBfOyfZiOAUNXTzWnPwPvqIsrJgrn8fuGl5C687HwlkN8dMBoVDYUAEsmvivncy1mvVb2y9Dqj+HwD0JVluQfGquYgmiTI64pzNPzl7cF+slWo60EPJ6zbJfJORUW335BozYxU/VdFfv9h7gIw8gLia3wgmMGW3zDT72pxeB8pAF
  template:
    metadata:
      name: kbot
      namespace: kbot
