#!/bin/bash
# для встановлення плагіну в систему виконати команду:
# mv kubeplugin kubectl-kubeplugin
# sudo cp kubectl-kubeplugin /usr/local/bin/

# Налаштування за замовчуванням
NAMESPACE="kube-system"
ACTION="top"
RESOURCE_TYPE="${1:-pods}" # Приймає тип ресурсу як аргумент або використовує pods за замовчуванням

# Перевірка наявності утиліти kubectl
if ! command -v kubectl &> /dev/null; then
    echo "Помилка: утиліту kubectl не знайдено в системі." >&2
    exit 1
fi

# Вивід заголовка
echo "Resource, Namespace, Name, CPU, Memory"

# Отримання та обробка статистики
kubectl "$ACTION" "$RESOURCE_TYPE" -n "$NAMESPACE" --no-headers 2>/dev/null | while read -r line; do
    if [ -n "$line" ]; then
        NAME=$(echo "$line" | awk '{print $1}')
        CPU=$(echo "$line" | awk '{print $2}')
        MEMORY=$(echo "$line" | awk '{print $3}')

        echo "$RESOURCE_TYPE, $NAMESPACE, $NAME, $CPU, $MEMORY"
    fi
done